server:
  port: 8082

spring:
  application:
    name: blog-service

  datasource:
    url: jdbc:postgresql://localhost:5433/blog_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: blog-service-user-events
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.microservice.events
        spring.json.value.default.type: com.microservice.events.UserEvent
        spring.json.use.type.headers: false

app:
  kafka:
    user-events-topic: user-events
